/*
 * Copyright 2013 Eqaula Tecnologías Cia Ltda
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.eqaula.glue.drools

import org.eqaula.glue.model.management.Method;
import org.eqaula.glue.model.management.Method.Wrap;

global java.util.List list

dialect "mvel"
 
rule "Red color"
no-loop true
    when
        m : Method(target.currentValue < target.value)
    then
        System.out.println( "---> Red " + m.target.value );
    modify ( m ) { addWrap(new Wrap("red"))};
end

rule "Yellow color"
no-loop true
    when
        m : Method(target.currentValue >= target.value && target.currentValue <= (target.value + 30))
    then
        System.out.println( "---> Yellow " + m.target.value );
    modify ( m ) { addWrap(new Wrap("yellow"))};
end

rule "Green color"
no-loop true
    when
        m : Method(target.currentValue > (target.value + 30))
    then
        System.out.println( "---> Yellow " + m.target.value );
    modify ( m ) { addWrap(new Wrap("green"))};
end